Northeastern-Electric-Racing/Embedded-Base

general/include/m24c32.h
general/src/m24c32.c
middleware/include/eepromdirectory.h
middleware/src/eepromdirectory.c

EEPROM drivers now work with addresses instead of pages.

Fixed eeprom drivers

---

general/include/pi4ioe.h
general/src/pi4ioe.c

Added uint8_t outputReg1 & outputReg2, removed cerberus macros, and adjusted write() to not override other bits when changing the desired bit.
Closes #2

#2: removed cerberus macros & new register variables

---

.github/workflows/build_cerberus.yml

I rebased main this time around so that it is working on a new build, I think this should work this time

adding cerberus build automation

---

middleware/include/timer.h
middleware/src/timer.c

apparently stdio has a timer_t and it was conflicting

changed name of timer struct

---

.github/ISSUE_TEMPLATE/bug-form.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/epic.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/ISSUE_TEMPLATE/spike.yml
.github/ISSUE_TEMPLATE/task.yml
.github/pull_request_template.md
dev/Dockerfile

Pretty small change, just moving dockerfile to this repo to consolidate our development environments and provide a single place for people to submit improvements to the development workflow.
Plan is that we implement the base docker image here, which gets built and pushed to docker hub when there is a new change. Then each firmware repo contains a docker-dev.yml that people can build locally themselves, or they can just run the base image.

Moving dockerfile to Embedded-Base

---

platforms/stm32g431/include/fdcan.h
platforms/stm32g431/src/fdcan.c

Added CAN drivers for the stm32g4 chip to the platform drivers.
I stole a bunch of code from stm32f4 CAN drivers, so most of the credit goes to the previous author. Also, if issues with those drivers come up, please let @Sabramz know so he can fix these drivers as well.

FDCAN drivers for stm32g4

---

general/src/ltc68041.c

fixed param

---

general/include/lsm6dso.h
platforms/stm32f405/src/can.c

Made CAN interrupts work by calling a HAL function that is linked to the interrupt in the linker.
It worked last time I ran it it oughta still work
Verify with devices other than another MPU

Hamza experimental

---

platforms/stm32g431/include/fdcan.h
platforms/stm32g431/src/fdcan.c

Added a function to receive fdcan messages in the fdcan driver

Get messages

---

platforms/stm32g431/include/fdcan.h
platforms/stm32g431/src/fdcan.c

Changes to fdcan drivers
- Case A
- Edge case
- ...

Some quick fdcan fixes

---

middleware/include/eepromdirectory.h
middleware/src/eepromdirectory.c

Included function for taking in array for structures for creating a partition
- Case A
- Edge case
- ...
#70

Creating eeprom_parition

---

general/include/max7314.h
general/src/max7314.c

Gpio expander drivers
May need to fix LSB and MSB orders :3.
- it builds
Closes #86

Max drivers

---

general/include/max7314.h
general/src/max7314.c

Set pin state

---

general/include/max7314.h
general/src/max7314.c

this is the last

---

cangen/can-messages/dti.yaml

Changed DTI CAN config format and comparing with develop/cangen instead of main.
Bing Chilling

Dti can msgs

---

general/include/max7314.h
general/src/max7314.c

im gonna force merge cuz it only affects my code

Quick fixes to the worst gpio expander drivers in history

---

general/include/sht30.h
general/src/sht30.c

Made Changes to Sht30 Driver to get communication working and properly decode the data coming in
stole pretty much this guys code https://github.com/henriheimann/stm32-hal-sht3x/blob/master/sht3x.c#L15
https://github.com/Northeastern-Electric-Racing/Embedded-Base/assets/113635669/bdcfe4b6-03fc-41c0-9876-08023ddeb298

Validate Sht30

---

platforms/stm32f405/include/can.h
platforms/stm32g431/include/fdcan.h

2 characters
- Case A
- Edge case
- ...

can extended

---

cangen/can-messages/mpu.yaml

Add Mode INdex

---

cangen/can-messages/wheel.yaml

Made the bit size be 8 for steering wheel buttons

change bit size for steering wheel

---

general/src/max7314.c

Fix max pins

---

platforms/stm32f405/include/can.h
platforms/stm32f405/src/can.c

extended can and sending extended

---

middleware/include/c_utils.h
middleware/src/c_utils.c

added endian swap function

---

general/include/pca9539.h
general/src/pca9539.c

Driver for pca gpio expander
https://www.ti.com/lit/ds/symlink/pca9539.pdf
My first ever driver so be very careful with this one lol.

Pca gpio expander

---

cangen/can-messages/bms.yaml
cangen/can-messages/charger.yaml
cangen/can-messages/mpu.yaml

Adds:
- BMS debugging yaml
- LV Voltage sense
- Fixes decoding of charging box data
This is the calypso deployed to car and charging cart.

Bms yaml and more

---

middleware/include/c_utils.h

idk nicks didnt work and mine does (unit tested) so L bozo @nwdepatie

fixed container of

---

cangen/README.md
cangen/can-messages/bms.json
cangen/can-messages/charger.json
cangen/can-messages/dti.json
cangen/can-messages/mpu.json
cangen/jsongen

- Some bool fields in cangen/can-messages were accidentially quoted. JSON files and `jsongen` have been updated to fix this.
- Updated README to include `Format.py`
- `serde_json` now properly deserializes `*.json`
Closes #164

Bug fix in JSON files

---

ftdi_flash.cfg
ner_environment/build_system/__init__.py
ner_environment/build_system/build_system.py
ner_environment/build_system/miniterm.py
ner_environment/requirements.txt

added flash cfg and ftdi support

added flash and ftdi support

---

general/include/ads131m04.h
general/src/ads131m04.c

Removed HAL-specific code in ads131m04 driver and added function pointers
Closes #155

Make ads131m driver agnostic

---

cangen/can-messages/bms.json

Make BMS faults bitwise.
Tested a few faults, all worky work.

bms bitwise

---

platforms/stm32f405/include/stm32xx_hal.h

Adapting Embedded Base for steering wheel code

Steering wheel

---

cangen/can-messages/mpu.json

Updated mpu JSON to support sending toque limit percentage through can

updated json to send torque limiting percentages

---

cangen/can-messages/bms.json

Just changed sys_inc_min to 0 (so we don't get decimal increments)
Closes #203

Fixed bms mock

---

.github/workflows/build_calypso.yml
cangen/can-messages/bms.json
cangen/can-messages/mpu.json

Add a calypso build check so people can see Harrison's beutiful deudulus error messages.
Add the Git versioning scheme both bc it needs to get merged and I wanna test the new actions.

Add A calypso build check, 

---

.github/workflows/build_cerberus.yml

Broke due to the Git revision PR.
Uses an adapted version of the new CI found in cerb.

Fix Cerberus CI

---

middleware/include/bitstream.h
middleware/include/c_utils.h
middleware/src/bitstream.c

- Added a bitstream data structure
- Not tested yet
Closes #238

Bitstream Datastructure

---

middleware/include/heap_ringbuffer.h
middleware/include/ringbuffer.h
middleware/src/heap_ringbuffer.c
middleware/src/ringbuffer.c

Fixed issues with indexing and element retrieval to ensure correct ordering, when the buffer wraps around. Improved how data is inserted and removed. Added checks to avoid invalid memory access.
Test Case: Ring Buffer Integration with Cell Data Logging on Shepherd-BMS
The ring buffer was tested as part of the cell data logging functionality on the Shepherd-BMS.

Updated Ring Buffer on Stack Implementation

---

cangen/can-messages/bms.json

We lost some BMS messages due to me being dumb dumb when resolving the new canJSON spec.  Add them back.
- Case A
- Edge case
- ...
Closes #246

resolve lost bms messages

---

general/include/INA226.h
general/src/INA226.c

I made some changes to the driver in the submodule on Cerberus, and now that the driver is working over there, I want to update it here. I'm not even sure these changes helped w/ anything but hey

Changes to INA226 driver

---

cangen/can-messages/bms.json

More bms fixups

---

cangen/can-messages/bms.json

- Added CAN message definition for PEC Error Count Notification in json file.

Added BMS PEC Count CAN message

---

middleware/include/c_utils.h

Added EXTRACT_BIT macro to c_utils.h for use in Cerberus

Added EXTRACT_BIT macro to c_utils.h

---

cangen/can-messages/mpu.json

add pump sensors

---

ner_environment/build_system/build_system.py

ftdi by default

---

platforms/stm32f405/src/can.c

Added stdio.h

---

platforms/stm32f405/src/can.c

Fixed warning

---

cangen/can-messages/bms.json

Made changes to the JSON for Pack Current. Changes correspond to changes made in the [24APackCurrent](https://github.com/Northeastern-Electric-Racing/Shepherd-BMS/pull/196) pull request in Shepard.

24A Pack Current

---

cangen/can-messages/bms.json

removed 6 segment

---

cangen/can-messages/energy_meter.json

Added formats for energy meter

---

cangen/can-messages/bms.json
cangen/can-messages/calypso_cmd.json
cangen/can-messages/charger.json
cangen/can-messages/dti.json
cangen/can-messages/energy_meter.json
cangen/can-messages/mpu.json
cangen/can-messages/msb.json

refactor to add arg to format
