Northeastern-Electric-Racing/Embedded-Base

- platforms/stm32f405/include/can.h
- platforms/stm32f405/src/can.c
The message queues weren't externally defined before, now they are
> Adding externally defined queues to allow us to actually build applications that use this CAN driver

- general/include/lsm6dso.h
- general/src/lsm6dso.c
synced function names in the imu so that it wouldnt throw an undefined error when i try to use it in cerberus
> sync imu names

- middleware/include/timer.h
- middleware/src/timer.c
Added timer functionality to repo. Should work for all chips, but does rely on specific reference to stmf4xx library (as all do). Not sure if middleware is best spot, feel free to suggest other location.
Plan to add more throughou error handling in future, both through STM HAL errors, and for addressing things like trying to read from inactive timer, etc. For now just want bare minimum functionality. 
Also, this ideally replaced both the NErduino timer class and the "Tri-state timer" struct i previously made in shepherd. Im not a fan of that, and the funcitonality can be replaced by just utilized the is_active" param properly.
> added timer.h/.c

- platforms/stm32f405/include/can.h
- platforms/stm32f405/src/can.c
Before we only were able to have 1 callback across all lines (i.e. global value), but now we are linking the callback to each hcan struct
> Adding the ability to create multiple CAN callbacks

- general/include/pi4ioe.h
- general/src/pi4ioe.c
This links to the Cerberus ticket to implement the PDU, but there are a bunch of PDU specific macros. I've moved the macros to the source files since the developer shouldn't care about these macros and it is only used for internal implementations.
> Moving macros to source files, linking to PDU implemnetation

- platforms/stm32f405/src/can.c
This should be a temporary fix but I've part of the send can message function is causing the application to hault indefinitely/crash. I commented it out which seems to work for now but we should 100% investigate if this is necessary or not
> Weird CAN behavior fix

- general/src/lsm6dso.c
- platforms/stm32f405/src/can.c
I added a flag into the Cerberus Makefile that flags every warning as an error to try and catch silly mistakes. It actually caught a few in this repo, so I wanted to make a PR fixing them so that Cerberus will build fine
> Fixing compilation warnings across the repo from Cerberus

- middleware/include/ringbuffer.h
- middleware/src/ringbuffer.c
I found some small errors I missed when trying to compile ringbuffer for Cerberus. Specifically:
* Forgot to include stdlib.h for malloc and calloc
* Never allocated memory for the buffer, tried to use calloc for the actual struct
* fixed return type of dequeue
> Fixing some minor errors with ringbuffer implementation

- platforms/stm32f405/include/can.h
made ID list const, this should always be the case, and i want to stop being spammed with the warnings in shepherd since the id list being passed in by apps is going to be const
> made param const

- general/include/lsm6dso.h
Fix for LSM6DSO driver to ping device ID
Pretty simple fix, also validated on hardware
> Fixing the address on lsm6dso to correct address

- general/include/ltc68041.h
- general/src/ltc68041.c
This simply restructured the ltc driver to accept the ltcconfig as a param instead of locally
Worked when testing on board
none
> removed ltc config from local --> app

- middleware/include/pid.h
- middleware/src/pid.c
> Add Generic PID Module

- general/include/mcp23008.h
- general/src/mcp23008.c
Built a drive to handle coms to the gpio exander chip
Just by way of needing function pointers have common parameters, this structure forces the application to have a wrapper for its i2c reads/writes. For example, using HAL, wed have to have the read/write functions we pass in internally handle i2c_handle. Not sure theres a way around this, just something to note though
Not tested/verified
IDK if we want to abstract any more APIs, for shepherd i dont see the need
- [x ] No merge conflicts
- [x ] All checks passing
- [ x] Remove any non-applicable sections of this …
> added read write and init

- dev/scripts/flash.sh
- dev/scripts/gdb.sh
My flashing alias didn't work, turns out openocd doesn't let you implement wildcards like bash into inputs
> Fixing alias issue with flashing and debug

- middleware/include/c_utils.h
- platforms/stm32f405/include/can.h
- platforms/stm32f405/src/can.c
Implementing our own `container_of` macro like the Linux Kernel has, and then using it for a better CAN callback implementation.
This is very very much not tested, I want to test on hardware before we merge in. I've used `container_of` a lot in the Linux Kernel and have been missing it in STM land, but just realized its one macro we could copy in. More info on what this macro does:
https://embetronicx.com/tutorials/p_language/c/understanding-of-container_of-macro-in-linux-kernel/
**NOTE** This did not work as intended lol. The macro itself works, but for this application it does not, see my comment below. 
User should go through the normal method of declaring an interrupt in STM32CubeMX, which autogenerates a callback for each CAN bus. STM actually intends for the user to input code in …
> Implementing more concise implementation of CAN callbacks

- .github/workflows/build_image.yml
- dev/Dockerfile
Auto build docker image with ghcr. Updates if anything in dev folder is changed, even across branches.  Those branches will have a different tag is all.
I am dumb apparently you can have public packages it is just very hidden in organization settings I only searched through repository settings.  Let me know if this works without authenticating, it worked for me I think.
Will add documentation switch to this with the eventual addition of compose.
Closes #52
> Automatically build docker image

- general/include/max7314.h
- general/src/max7314.c
> MAX7314 GPIO expander 

- cangen/can-messages/charger.yaml
- cangen/can-messages/dti.yaml
- middleware/include/c_utils.h
- middleware/src/c_utils.c
Reverses the bit order each bit addressable byte of the DTI yaml, as it is in the opposite order as is documented.
Turns out calypso always reads left to right, while for some reason the memcpy and can being sent spits out the bits right to left (per byte) probably as data is stored most to least significant bits.  Very confusing and probably a calypso way to fix it, however it is much easier if we standardize bits to be sent should be ordered 
Example: 
Fuse buffer created: `1(A) 1(B) 1101111(E) ` 
Fuse buffer sent over can `1(B) 1101111` `00000001(A) `
After this PR the buffer is the same, but by reversing each bit we get:
`1(A) 1(B) 110111` `1(E) 00000000`
If this makes sense to ppl I will make the followup MPU PR that reverses both fuse and shutdown buffer using the function included …
> Yaml refresh

- general/include/LTC4015.h
- general/include/lsm6dso.h
- general/include/ltc68041.h
- general/include/m24c32.h
- general/include/max7314.h
- general/include/pi4ioe.h
- general/include/sht30.h
- general/include/stm32xx_hal.h
- platforms/stm32f405/include/can.h
- platforms/stm32f405/include/stm32xx_hal.h
- platforms/stm32g431/include/fdcan.h
- platforms/stm32g431/include/stm32xx_hal.h
Added in an ifdef that detects which STM platform we are building for to make the drivers somewhat agnostic to which STM they are running on. This is because the different peripherals in the STM we talk thru are standardized across the STM lineup and should not have to make essentially the exact same code to get a project to build except change the HAL include.
Note that I had to add in this include into every include directory to make specifically the Charger firmware build, since it doesn't use any drivers. This can be easily fixed in the future by just putting all the drivers into one directory and eliminating the platforms directory OR moving everything under an `stm32` platform to set a precedent for using other types of chips, i.e. ESP32
- Cerberus built
- Iroh built
- Shepherd BMS …
> Generic drivers

- general/include/ads131m04.h
- general/src/ads131m04.c
I should've checked this before smh, now it actually builds
> Changing some stuff to make the ADC driver build

- general/include/ltc68041.h
- general/src/ltc68041.c
This is a small PR to change some parameters:
1. Changed sampling mode of auxiliary inputs to filtered
2. Exposed clraux function in header
- Tested on shepherd and it worked with current configuration
> Changing to filtered and exposing clraux as a function

- general/include/vl6180x_api.h
- general/include/vl6180x_cfg.h
- general/include/vl6180x_def.h
- general/include/vl6180x_i2c.h
- general/include/vl6180x_platform.h
- general/include/vl6180x_types.h
- general/src/vl6180x_api.c
- general/src/vl6180x_i2c.c
Uses the ST driver, commited directly to Embedded Base (ew).  All changes from upstream marked with a comment that contains NER.
> initial vl6180 from st stsw-img0003

- cangen/CANField.py
- cangen/CANMsg.py
- cangen/README.md
- cangen/Result.py
- cangen/RustSynth.py
- cangen/YAMLParser.py
- cangen/can-messages/calypso_cmd.yaml
- cangen/can-messages/dti.yaml
- cangen/can-messages/mpu.yaml
Add bidirectionality to calypso.
Replicates most functionaly of decoding with slight tweaks here and there, otherwise somewhat duplication of decoding with just changing class names and whatnot,
> Rust synth encoding

- ftdi_flash.cfg
- ner_environment/build_system/build_system.py
- ner_environment/ner_setup.py
- openocd.cfg
Fixups for NER build.  Mainly switch to WSL as it is closer to Linux. See accompanying [Cerb PR](https://github.com/Northeastern-Electric-Racing/Cerberus/pull/213).
> Ner build fixups

- ner_environment/build_system/__init__.py
- ner_environment/build_system/build_system.py
- ner_environment/build_system/miniterm.py
- ner_environment/requirements.txt
- ner_environment/setup.py
Pivots from Argparser to Typer, as per a recommendation from Nick
Slightly better organization/ease of use for adding commands and options, but big gain is that it allows for a much more attractive CLI UI
Other changes:
- switch WSL detection function to a slightly simpler way (NEEDS TESTING)
- adds an update function that redoes the setup script so that ner/venv shouldnt really need to be deleted nor should ner_setup need to be rerun often
> Convert NER build system to Typer

- general/include/lsm6dso.h
- general/src/lsm6dso.c
Made imu platform agnostic
Closes #156
> Platform Agnostic IMU

- general/include/INA226.h
- general/src/INA226.c
- Added missing #endif to INA226.h
- Added #include <stdint.h> and #include <math.h> to INA226.h
- Fixed ina226_reset, ina226_read_manufacturer_id, and ina226_read_die_id params
These issues were preventing me from building Cerberus
Closes # (#152)
> Updated INA226 driver

- cangen/can-messages/mpu.json
- Added LV Sense SOC to `mpu.json` (See https://github.com/Northeastern-Electric-Racing/Cerberus/issues/219)
Closes https://github.com/Northeastern-Electric-Racing/Cerberus/issues/219
> Added LV Sense SOC to cerb CAN spec

- dev/Dockerfile
- dev/scripts/gdb.sh
- ner_environment/build_system/build_system.py
- ner_environment/build_system/miniterm.py
This adds a command that fixed git ownership issues in app repos. Not too sure about the science behind it but it worked so LGTM
> added safe dir

- cangen/README.md
- cangen/can-messages/bms.json
- Calypso can now read the bits of a CANPoint as an IEEE754 32-bit float (see https://github.com/Northeastern-Electric-Racing/Calypso/issues/75).
- To accommodate this, a new field has been added to the CAN spec. ieee754_f32 is an optional boolean field in the CANPoint spec, which indicates that the CANPoint should be decoded as an f32.
- `BMS/Debug/Spare3` is now an IEEE754 32-bit float, for testing.
- CANPoints that wish to use this feature must specify the `ieee754_f32` field as `true` in the JSON.
Closes [Calypso #75](https://github.com/Northeastern-Electric-Racing/Calypso/issues/75)
> Added support to decode IEEE754 32-bit floats over CAN

- general/include/pca9539.h
- general/src/pca9539.c
small structural changes to pca driver to remove any references to STM HAL and make it fully platform agnostic
There is a follow-up pr in Cerb fixes pdu to use this new driver (has been tested)
> Fixes PCA driver

- cangen/can-messages/msb.json
Added four CAN messages in msb.json for the Front Right (FR), Front Left (FL), Back Right (BR), and Back Left (BL) MSB board orientation data.
Verified that the new JSON entries correctly define IMU orientation fields using Calypso.
> Added CAN Messages for MSB Orientation Data in msb.json

- cangen/can-messages/mpu.json
- MPU faults are currently bitwise according to Cerberus documentation, but they were not send this way in the JSON. So, MPU faults were changed to bitwise in the JSON, similar to how they are currently set up in bms.json.
Not tested yet
Closes #225
> Changed MPU faults to bitwise

- middleware/include/bitstream.h
- middleware/src/bitstream.c
- Added `bool overflow` to the bitstream struct. If `bitstream_add()` is called for a value larger than the maximum possible value for the allotted number of bits, `bitstream->overflow` is set to true. No error is returned, but the value of the input is capped at `pow(2, num_bits) - 1` (rather than overflowing to 0).
> Added Overflow Property to Bitstream

- platforms/stm32f405/include/can.h
- platforms/stm32f405/src/can.c
Added support for extended CAN IDs. `can_msg_t` now has a `id_is_extended` bool, which should be manually set when the struct instance is created. The bool is evaluated by `can_send_msg()`, which sends the correct type of message accordingly. Also, a `can_add_filter_extended()` function was created.
Not tested yet
Implement in the other repos
Closes #247 (Once implemented in other repos)
> Extended CAN IDs

- middleware/src/bitstream.c
Fixes for segment 24a.
Fix bitstream by ignoring the global overflow state.  also always increment the bits.
> make bitstream not act on prev overflow

- platforms/stm32f405/include/can.h
- platforms/stm32f405/src/can.c
Edited how extended CAN IDs are added to filters. Hopefully fixes thing
Will test soon
If it works on Shepherd, I'll change the Cerb PR as well
> Extended CAN IDs Fix?

- platforms/stm32f405/src/can.c
Small PR for extended CAN IDs build warnings I didn't fix earlier.
> Fixed Build Warnings

- general/include/tca9539.h
Small PR to change TCA9539 register macro names to be consistent w/ what the registers are called in the datasheet
> Change TCA9539 Macro Naming

- cangen/can-messages/mpu.json
Made shutdown and fuse CAN messages consistent with Cerberus code
Also added a new debug message that just reads all GPIO expander pins. Corresponding changes made on `final-bringup` on cerb
> Shutdown and Fuses JSON

- middleware/include/c_utils.h
Fixes EXTRACT_BIT macro (for how it is used in pdu.c)
I'm 99% sure its only used in pdu.c so won't break anything
> Fix EXTRACT_BIT() macro

- middleware/include/bitstream.h
- middleware/src/bitstream.c
Added signed int support to bitstream.c using _Generic. bitstream_add() is a macro now, but everything should still work the same. I also removed bitstream_read() since it's not really useful and would probably just be confusing now that bitstream also supports signed ints.
Not tested yet
> Added signed int support to bitstream

- platforms/stm32h563/include/fdcan.h
- platforms/stm32h563/include/stm32xx_hal.h
- platforms/stm32h563/src/fdcan.c
Created two new files:
`platforms/stm32h563/fdcan.h`
`platforms/stm32h563/fdcan.c`
These files were based off of the stm32g431 FDCAN files, but changes were made to make the API more similar to STM32F4 `can.c`.
Obv not tested yet.
> Added FDCAN support for STM32H563

- platforms/stm32h563/include/fdcan.h
- platforms/stm32h563/src/fdcan.c
Whoops
Was getting build warnings in Cerb-2.0 due to stuff in `fdcan.c`:
- Forgot to include `<stdio.h>`
- Used `%d` instead of `%ld` in printf()
Fixed both those things
Also, added an hcan param to can_init() so you don't have to manually set `can1.hcan = hcan` in the application layer. Figured this was cleaner.
> Fixed build warnings caused by STM32H563 fdcan.c.

- middleware/include/timer.h
Changed STM32 HAL #include to not be platform-specific so you can use `timer.h` in any repo
> Changed STM32 HAL #include to not be platform-specific

- middleware/include/timer.h
Added `#include <stdint.h>` in timer.h to fix build errors.
> Added #include <stdint.h> to timer.h
